# This file was generated by GoReleaser. DO NOT EDIT.
cask "skill-detector" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "8402c21486133bbd584e5c3d1001f1d5c7906a29ce214dab914b4377b2242801"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/skilltrust/skill-detector"
    end
    on_arm do
      sha256 "f5469f5affbf8baabdde4ef555c5b33034f70c060912659e76e5b797efd8aeae"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/skilltrust/skill-detector"
    end
  end

  on_linux do
    on_intel do
      sha256 "179a9bd6d54487111559baf6b69c84787e8faaae276b2cb83678f1737a70ae60"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_linux_amd64.tar.gz",
        verified: "github.com/skilltrust/skill-detector"
    end
    on_arm do
      sha256 "2617eda272432b3c84df919752a11448ebb6c42b4e3933068dd7d9b9750ea92f"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_linux_arm64.tar.gz",
        verified: "github.com/skilltrust/skill-detector"
    end
  end

  name "skill-detector"
  desc "Detect security threats in AI skill packages"
  homepage "https://github.com/skilltrust/skill-detector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skill-detector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skill-detector"]
    end
  end

  # No zap stanza required

end
