# This file was generated by GoReleaser. DO NOT EDIT.
cask "skill-detector" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "5efb25f08c57a9f292a2369c1d4e96b3e81cc27e78ec907c61aa73abb27bf0dd"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/skilltrust/skill-detector"
    end
    on_arm do
      sha256 "ce40354cc92cb035784258df1bb49a57654e6d18240d718589fab406d6fc10ab"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/skilltrust/skill-detector"
    end
  end

  on_linux do
    on_intel do
      sha256 "d2b1e9e3420bc8705747c0756590fc520d6fae3f5e3a054f6dcfb48ab1823863"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_linux_amd64.tar.gz",
        verified: "github.com/skilltrust/skill-detector"
    end
    on_arm do
      sha256 "ec1a80c166e12502e86946a1e42b82e0c77d3791f75edc0b4229fb1fbe157de2"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_linux_arm64.tar.gz",
        verified: "github.com/skilltrust/skill-detector"
    end
  end

  name "skill-detector"
  desc "Detect security threats in AI skill packages"
  homepage "https://github.com/skilltrust/skill-detector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skill-detector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skill-detector"]
    end
  end

  # No zap stanza required

end
