# This file was generated by GoReleaser. DO NOT EDIT.
cask "skill-detector" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "45fde172bc6f1db8f7a6d1dec40ac1368b2dc9749570ec4cfb6063d5fa4f4a20"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "72337443d58a7e4a70f03b1d185bb1b479f8b07835d818ca307646fbe5ce251d"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3545191a1746f371f31acf63df622a1ea48cad2fee0d7be7c6d6ad39329c02e6"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7aef7325bf152d9c378bbaa7717b18f19c0df080a60e0d67bcdb93611616844f"
      url "https://github.com/skilltrust/skill-detector/releases/download/v#{version}/skill-detector_#{version}_linux_amd64.tar.gz"
    end
  end

  name "skill-detector"
  desc "Detect security threats in AI skill packages"
  homepage "https://github.com/skilltrust/skill-detector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skill-detector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/skill-detector"]
    end
  end

  # No zap stanza required
end
